spring:
  datasource:
    url: jdbc:mysql://localhost:3306/town_restaurants
    username: root
    password: yerevan21

  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
       mail:
         smtp:
          auth: true
          starttls:
            enable: true


#  jpa:
#    hibernate:
#      ddl-auto: create

logging:
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz
      max-file-size: 10MB
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level - %msg%n"
  level:
    root: info
    am.itspace: info

#  liquibase:
#    change-log: classpath:db/changelog/migration.xml

project:
  images:
    folder: /Users/annakhachatryan/Library/Application Support/JetBrains/town-restaurants-parent/town-restaurants-web/src/main/resources/static/image

#http://localhost:8080/api/v1/swagger-ui/index:
#  html: